pr: none
trigger:
- try

variables:
- group: prod-credentials

jobs:
- job: macOS
  timeoutInMinutes: 600
  pool:
    vmImage: macos-10.15
  steps:
  - template: steps/run.yml
  strategy:
    matrix:
      # OSX builders running tests, these run the full test suite.
      # NO_DEBUG_ASSERTIONS=1 to make them go faster, but also do have some
      # runners that run `//ignore-debug` tests.
      #
      # Note that the compiler is compiled to target 10.8 here because the Xcode
      # version that we're using, 8.2, cannot compile LLVM for OSX 10.7.
      x86_64-apple:
        SCRIPT: ./x.py test
        RUST_CONFIGURE_ARGS: --build=x86_64-apple-darwin --enable-sanitizers --enable-profiler --set rust.jemalloc
        RUSTC_RETRY_LINKER_ON_SEGFAULT: 1
        MACOSX_DEPLOYMENT_TARGET: 10.8
        MACOSX_STD_DEPLOYMENT_TARGET: 10.7
        NO_LLVM_ASSERTIONS: 1
        NO_DEBUG_ASSERTIONS: 1

      dist-x86_64-apple:
        SCRIPT: ./x.py dist
        RUST_CONFIGURE_ARGS: --target=aarch64-apple-ios,x86_64-apple-ios --enable-full-tools --enable-sanitizers --enable-profiler --set rust.jemalloc
        RUSTC_RETRY_LINKER_ON_SEGFAULT: 1
        MACOSX_DEPLOYMENT_TARGET: 10.7
        NO_LLVM_ASSERTIONS: 1
        NO_DEBUG_ASSERTIONS: 1
        DIST_REQUIRE_ALL_TOOLS: 1

      dist-x86_64-apple-alt:
        SCRIPT: ./x.py dist
        RUST_CONFIGURE_ARGS: --enable-extended --enable-profiler --set rust.jemalloc
        RUSTC_RETRY_LINKER_ON_SEGFAULT: 1
        MACOSX_DEPLOYMENT_TARGET: 10.7
        NO_LLVM_ASSERTIONS: 1
        NO_DEBUG_ASSERTIONS: 1

# The macOS and Windows builds here are currently disabled due to them not being
# overly necessary on `try` builds. We also don't actually have anything that
# consumes the artifacts currently. Perhaps one day we can reenable, but for now
# it helps free up capacity on Azure.
# - job: macOS
#   timeoutInMinutes: 600
#   pool:
#     vmImage: macos-10.15
#   steps:
#   - template: steps/run.yml
#   strategy:
#     matrix:
#       dist-x86_64-apple:
#         SCRIPT: ./x.py dist
#         RUST_CONFIGURE_ARGS: --target=aarch64-apple-ios,armv7-apple-ios,armv7s-apple-ios,i386-apple-ios,x86_64-apple-ios --enable-full-tools --enable-sanitizers --enable-profiler --set rust.jemalloc
#         DEPLOY: 1
#         RUSTC_RETRY_LINKER_ON_SEGFAULT: 1
#         MACOSX_DEPLOYMENT_TARGET: 10.7
#         NO_LLVM_ASSERTIONS: 1
#         NO_DEBUG_ASSERTIONS: 1
#         DIST_REQUIRE_ALL_TOOLS: 1
#
#       dist-x86_64-apple-alt:
#         SCRIPT: ./x.py dist
#         RUST_CONFIGURE_ARGS: --enable-extended --enable-profiler --set rust.jemalloc
#         DEPLOY_ALT: 1
#         RUSTC_RETRY_LINKER_ON_SEGFAULT: 1
#         MACOSX_DEPLOYMENT_TARGET: 10.7
#         NO_LLVM_ASSERTIONS: 1
#         NO_DEBUG_ASSERTIONS: 1
#
# - job: Windows
#   timeoutInMinutes: 600
#   pool:
#     vmImage: 'vs2017-win2016'
#   steps:
#   - template: steps/run.yml
#   strategy:
#     matrix:
#       dist-x86_64-msvc:
#         RUST_CONFIGURE_ARGS: >
#           --build=x86_64-pc-windows-msvc
#           --target=x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
#           --enable-full-tools
#           --enable-profiler
#         SCRIPT: python x.py dist
#         DIST_REQUIRE_ALL_TOOLS: 1
#         DEPLOY: 1
#
#       dist-x86_64-msvc-alt:
#         RUST_CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc --enable-extended --enable-profiler
#         SCRIPT: python x.py dist
#         DEPLOY_ALT: 1
